//! Validates `bootstrap/corpus/` (DESIGN.md's "Self-hosting bootstrap
//! corpus" section) against THIS crate's own real `Lexer`+`Parser` —
//! every `<name>.plum` fixture must still render (via `plum_syntax::
//! render::render_program`/`render_tokens`, the exact same canonical
//! forms `plum dump-ast`/`plum dump-tokens` print) to exactly its
//! paired `<name>.expected`/`<name>.tokens` golden files.
//!
//! Two jobs at once, for both goldens: (1) an ordinary regression test
//! — if a future change to THIS lexer/parser ever shifts what it
//! produces for one of these fixtures, this fails immediately, here,
//! rather than being silently absorbed; (2) the corpus's own self-check
//! — every golden file was generated BY these same rendering paths, so
//! this test is what keeps the corpus internally consistent as
//! fixtures are added/edited over time. Once a self-hosted Plum
//! lexer/parser exists (Stage 1 of the self-hosting bootstrap), it gets
//! checked against these SAME golden files independently — this test
//! doesn't change at all when that happens, it just stops being the
//! only thing validating the corpus. `.tokens` goldens exist
//! specifically so the SELF-HOSTED LEXER gets its own real pass/fail
//! signal before the self-hosted parser is far enough along to expose
//! a lexer bug indirectly (see `run_dump_tokens`'s own doc comment in
//! `plumc::main`) — not every fixture strictly needs one (a lexer bug
//! would eventually surface as an AST mismatch too), but generating
//! both goldens for every fixture is cheap and uniform, so there's no
//! reason to track two different fixture sets.

use plum_syntax::lexer::Lexer;
use plum_syntax::parser::Parser;
use plum_syntax::render::{render_program, render_tokens};
use std::path::{Path, PathBuf};

fn corpus_dir() -> PathBuf {
    // `CARGO_MANIFEST_DIR` is this crate's own directory
    // (`crates/plum-syntax`) — `bootstrap/corpus` lives two levels up,
    // at the repo root, deliberately outside any one crate (see
    // DESIGN.md: the corpus is meant to outlive any single
    // implementation, Rust's included).
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../bootstrap/corpus")
}

/// Every `.plum` fixture path under `corpus_dir()`, discovered by
/// walking its topic subdirectories — new fixtures need no separate
/// registration anywhere, just a `<name>.plum`/`<name>.expected` pair
/// dropped into the right topic directory.
fn discover_fixtures() -> Vec<PathBuf> {
    let mut out = Vec::new();
    let root = corpus_dir();
    let topics = std::fs::read_dir(&root).unwrap_or_else(|e| panic!("failed to read corpus dir {root:?}: {e}"));
    for topic in topics {
        let topic = topic.unwrap_or_else(|e| panic!("failed to read a corpus topic entry: {e}"));
        if !topic.file_type().unwrap().is_dir() {
            continue;
        }
        for entry in std::fs::read_dir(topic.path()).unwrap_or_else(|e| panic!("failed to read {:?}: {e}", topic.path())) {
            let entry = entry.unwrap_or_else(|e| panic!("failed to read a fixture entry: {e}"));
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "plum") {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}

#[test]
fn every_corpus_fixture_matches_its_golden_ast_dump() {
    let fixtures = discover_fixtures();
    assert!(!fixtures.is_empty(), "found zero .plum fixtures under {:?} — corpus discovery is broken", corpus_dir());

    let mut failures = Vec::new();
    for plum_path in &fixtures {
        let expected_path = plum_path.with_extension("expected");
        let src = std::fs::read_to_string(plum_path).unwrap_or_else(|e| panic!("failed to read {plum_path:?}: {e}"));
        let expected = std::fs::read_to_string(&expected_path).unwrap_or_else(|_| {
            panic!("missing golden file {expected_path:?} for fixture {plum_path:?} — every .plum fixture needs a paired .expected (generate via `plum dump-ast <file> > <file:.plum=.expected>`)")
        });

        let tokens = Lexer::new(&src).tokenize();
        let mut parser = Parser::new(tokens);
        let actual = match parser.parse_program() {
            Ok(program) => render_program(&program),
            Err(e) => {
                failures.push(format!("{plum_path:?}: failed to parse: {e}"));
                continue;
            }
        };
        let expected = expected.trim_end_matches('\n');
        if actual != expected {
            failures.push(format!(
                "{plum_path:?}: golden mismatch\n  expected: {expected}\n  actual:   {actual}"
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} corpus fixture(s) failed:\n{}",
        failures.len(),
        fixtures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_corpus_fixture_matches_its_golden_token_dump() {
    let fixtures = discover_fixtures();
    assert!(!fixtures.is_empty(), "found zero .plum fixtures under {:?} — corpus discovery is broken", corpus_dir());

    let mut failures = Vec::new();
    for plum_path in &fixtures {
        let tokens_path = plum_path.with_extension("tokens");
        let src = std::fs::read_to_string(plum_path).unwrap_or_else(|e| panic!("failed to read {plum_path:?}: {e}"));
        let expected = std::fs::read_to_string(&tokens_path).unwrap_or_else(|_| {
            panic!("missing golden file {tokens_path:?} for fixture {plum_path:?} — every .plum fixture needs a paired .tokens (generate via `plum dump-tokens <file> > <file:.plum=.tokens>`)")
        });

        let tokens = Lexer::new(&src).tokenize();
        let actual = render_tokens(&tokens);
        let expected = expected.trim_end_matches('\n');
        if actual != expected {
            failures.push(format!(
                "{plum_path:?}: golden mismatch\n  expected: {expected}\n  actual:   {actual}"
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} corpus fixture(s) failed:\n{}",
        failures.len(),
        fixtures.len(),
        failures.join("\n")
    );
}
